// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBM3JRHlreKsFsYJQtgRtL4KZv2xbh5lk',
    appId: '1:708303731331:web:3d58ff0e6873e10313f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    authDomain: 'meet-d8070.firebaseapp.com',
    storageBucket: 'meet-d8070.firebasestorage.app',
    measurementId: 'G-TNB9E6PT2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYNBs1tKvYVtmJFJin7w3aP803kQEvio',
    appId: '1:708303731331:android:b6aa4d507602ba1a13f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    storageBucket: 'meet-d8070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC105IESZjuxJ4VFj4QytvKv8PiQJffwqM',
    appId: '1:708303731331:ios:6ddb5678e17b8ed413f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    storageBucket: 'meet-d8070.firebasestorage.app',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC105IESZjuxJ4VFj4QytvKv8PiQJffwqM',
    appId: '1:708303731331:ios:6ddb5678e17b8ed413f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    storageBucket: 'meet-d8070.firebasestorage.app',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBM3JRHlreKsFsYJQtgRtL4KZv2xbh5lk',
    appId: '1:708303731331:web:b619717cbe421f6013f9b6',
    messagingSenderId: '708303731331',
    projectId: 'meet-d8070',
    authDomain: 'meet-d8070.firebaseapp.com',
    storageBucket: 'meet-d8070.firebasestorage.app',
    measurementId: 'G-HGW2PK6JG3',
  );
}
